### ISSUE TITLE
divide by zero crash

### ISSUE THREAD

**Issue by garogan** [kwpugh/SimpleBackpack#38]
Noticed a bug, if you try to put an item frame into a void bundle, CTD with divide by zero exception

**Comment by kwpugh** [comment]
Log or crash report

**Comment by garogan** [comment]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 4/20/22, 7:30 PM
Description: Container click

java.lang.ArithmeticException: / by zero
	at com.kwpugh.simple_backpack.bundle.VoidBundleItem$BundleInventory.addStack(VoidBundleItem.java:295)
	at com.kwpugh.simple_backpack.bundle.VoidBundleItem.addToBundle(VoidBundleItem.java:143)
	at com.kwpugh.simple_backpack.bundle.VoidBundleItem.method_31566(VoidBundleItem.java:92)
	at net.minecraft.class_1799.method_31576(class_1799.java:384)
	at net.minecraft.class_1703.method_30010(class_1703.java:411)
	at net.minecraft.class_1703.method_7593(class_1703.java:295)
	at net.minecraft.class_636.method_2906(class_636.java:417)
	at net.minecraft.class_465.method_2383(class_465.java:565)
	at net.minecraft.class_465.method_25406(class_465.java:534)
	at net.minecraft.class_312.method_1605(class_312.java:96)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:96)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1147)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.kwpugh.simple_backpack.bundle.VoidBundleItem$BundleInventory.addStack(VoidBundleItem.java:295)
	at com.kwpugh.simple_backpack.bundle.VoidBundleItem.addToBundle(VoidBundleItem.java:143)
	at com.kwpugh.simple_backpack.bundle.VoidBundleItem.method_31566(VoidBundleItem.java:92)
	at net.minecraft.class_1799.method_31576(class_1799.java:384)
	at net.minecraft.class_1703.method_30010(class_1703.java:411)
	at net.minecraft.class_1703.method_7593(class_1703.java:295)
	at net.minecraft.class_636.method_2906(class_636.java:417)
	at net.minecraft.class_465.method_2383(class_465.java:565)
	at net.minecraft.class_465.method_25406(class_465.java:534)
	at net.minecraft.class_312.method_1605(class_312.java:96)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:96)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)

-- Click info --
Details:
	Menu Type: minecraft:generic_9x6
	Menu Class: net.minecraft.class_1707
	Slot Count: 90
	Slot: 86
	Button: 1
	Type: PICKUP
Stacktrace:
	at net.minecraft.class_1703.method_7593(class_1703.java:295)
	at net.minecraft.class_636.method_2906(class_636.java:417)
	at net.minecraft.class_465.method_2383(class_465.java:565)
	at net.minecraft.class_465.method_25406(class_465.java:534)
	at net.minecraft.class_312.method_1605(class_312.java:96)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:96)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1147)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_476
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:96)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1147)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Deegenerate'/207, l='ClientLevel', x=3047.30, y=67.00, z=8031.30]]
	Chunk stats: 4096, 2125
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,72,-48), Section: (at 0,8,0 in 1,4,-3; chunk contains blocks 16,-64,-48 to 31,319,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 1171089 game time, 1597917 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2270905328 bytes (2165 MiB) / 4429185024 bytes (4224 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f14
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9649
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9bc4
	Graphics card #1 versionInfo: DriverVersion=27.20.100.9664
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 40529.69
	Virtual memory used (MB): 22099.53
	Swap memory total (MB): 8000.00
	Swap memory used (MB): 561.36
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionaladditions: Additional Additions 3.0.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
		appleskin: AppleSkin 2.4.0+mc1.18.2
		architectury: Architectury 4.1.44
		autoconfig1u: Auto Config v1 Updated 3.4.0
		balm-fabric: Balm 3.0.0+0
		blue_endless_jankson: jankson 1.2.1
		byg: Oh The Biomes You'll Go 1.4-RC-8
		caffeineconfig: CaffeineConfig 1.1.0
		cardinal-components-base: Cardinal Components API (base) 4.1.4
		cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		carrier: Carrier 1.10.0
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		cloth-config-lite: cloth-config-lite 2.0.6
		coat: Coat 1.0.0-beta.17+mc1.18.2
		colytra: Colytra 2.1.1-1.18.1
		com_electronwill_night-config_core: core 3.6.4
		com_electronwill_night-config_toml: toml 3.6.4
		config2brigadier: Config to Brigadier 1.0.2
		crowdin-translate: CrowdinTranslate 1.4+1.18.2
		cullleaves: Cull Leaves 2.3.2
		customportalapi: Custom Portal Api 0.0.1-beta50-1.18
		denseores: Dense Ores: Refabricated 1.2.2+1.18.2
		disenchanter: Disenchanter 0.1.5+1.18
		durabilityviewer: Giselbaers Durability Viewer 1.18.2-fabric0.47.10-1.10.3
		fabric: Fabric API 0.50.0+1.18.2
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.0+2373a54560
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
		fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.3+d82b939260
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.11+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.17+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.14+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.4.0+4457765560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.11+91896a4960
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
		fabric-language-kotlin: Fabric Language Kotlin 1.7.2+kotlin.1.6.20
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.0+81ea5b3c60
		fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.0+fe4ddef060
		fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.17+d8c7b9ae60
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
		fabric-rendering-v1: Quilted Fabric Rendering (v1) 2.0.0+1.18.2-SNAPSHOT
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.0+1f6558e860
		fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.0+2373a54560
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+40c91ec860
		fabricloader: Fabric Loader 0.13.3
		fabrilousupdater: FabrilousUpdater 2.6+1.18.2
		gbfabrictools: GBfabrictools 1.3.4+1.18.2
		gud_recipe_confidence: Recipe Confidence 1.0.2
		healthcare: Health Care 1.0.11
		horsebuff: HorseBuff 1.2.3
		incubus_core: Incubus Core 1.6.6+1.18.2
		inmis: Inmis 2.5.3-1.18.2
		inspecio: Inspecio 1.3.0+1.18
		iris: Iris 1.2.2-build.32
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		journeymap-api-fabric: JourneyMap API 1.18.2-1.8-fabric-SNAPSHOT
		journeymap-fabric: Journeymap 5.8.1beta4
		libgui: LibGui 5.3.1+1.18
		libninepatch: LibNinePatch 1.1.0
		limitless: limitless 1.6.7
		lithium: Lithium 0.7.9
		midnightlib: MidnightLib 0.4.0
		minecraft: Minecraft 1.18.2
		modmanager: Mod Manager 1.2.3+1.18
		modmenu: Mod Menu 3.1.1
		moretags: More Tags 3.0.3
		mostructures: Mo' Structures 1.4.1+1.18.2
		nbtcrafting: NBT Crafting 2.1.3+mc1.18.2
		net_auoeke_reflect: reflect 4.6.0
		net_gudenau_lib_unsafe: unsafe 1.7.1
		net_hypixel_hypixel-api-core: hypixel-api-core 4.1
		net_hypixel_hypixel-api-transport-apache: hypixel-api-transport-apache 4.1
		omega-config: OmegaConfig 1.2.3-1.18.1
		omega-config-gui: Omega Config GUI 1.2.3-1.18.1
		org_anarres_jcpp: jcpp 1.4.14
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.20
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.20
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.0
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		org_joml_joml: joml 1.10.2
		osmium: Osmium 1.3.1-1.18.2
		packet_tweaker: Packet Tweaker 0.2.0+1.18-pre1
		phosphor: Phosphor 0.8.1
		quilt_base: Quilt Base API 1.0.0+1.18.2-SNAPSHOT
		quilt_client_command: Quilt Client Command API 1.0.0+1.18.2-SNAPSHOT
		quilt_command: Quilt Command API 1.0.0+1.18.2-SNAPSHOT
		quilt_lifecycle_events: Quilt Lifecycle Events 1.0.0+1.18.2-SNAPSHOT
		quilt_resource_loader: Quilt Resource Loader 1.0.0+1.18.2-SNAPSHOT
		quilt_tags: Quilt Tags API 1.0.0+1.18.2-SNAPSHOT
		quilt_tooltip: Quilt Tooltip API 1.0.0+1.18.2-SNAPSHOT
		quilted-fabric-api-base: Quilted Fabric API Base 1.0.0+1.18.2-SNAPSHOT
		quilted-fabric-command-api-v1: Quilted Fabric Command API (v1) 2.0.0+1.18.2-SNAPSHOT
		quilted-fabric-lifecycle-events-v1: Quilted Fabric Lifecycle Events (v1) 2.0.1+1.18.2-SNAPSHOT
		quilted-fabric-resource-loader-v0: Quilted Fabric Resource Loader (v0) 1.0.0+1.18.2-SNAPSHOT
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reeses-sodium-options: Reese's Sodium Options 1.4.2
		rocks: This Rocks! 1.6.0
		roughlyenoughitems: Roughly Enough Items 8.0.442
		rpgstats: RPGStats 4.3.8+1.18.2
		satin: Satin 1.7.2
		server_translations_api: Server Translations API 1.4.10+1.18.2
		silkspawners: SilkSpawners 1.1.1
		simple_backpack: SimpleBackpack 1.2.35
		sodium: Sodium 0.4.1+build.15
		sodium-extra: Sodium Extra 0.4.3
		spiceoffabric: Spice of Fabric 1.5.2+1.18.2
		stacc: Stacc 1.3.0
		stacker: Stacker 2.1.3
		stepup: StepUp 1.18.2-fabric0.47.10-1.1
		subterrestrial: Subterrestrial 1.0.2
		terrablender: TerraBlender 1.1.0.99
		the_aether: Paradise Lost 1.6.8+1.18.2
		timber: Timber 1.2.0+1.18.2
		trinkets: Trinkets 3.3.0
		tweed4_annotated: tweed4_annotated 1.3.0+mc1.18.2
		tweed4_base: tweed4_base 1.5.0+mc1.18.2
		tweed4_data: tweed4_data 1.2.1+mc1.18.2
		tweed4_data_hjson: tweed4_data_hjson 1.1.0+mc1.18.2
		tweed4_tailor_coat: tweed4_tailor_coat 1.1.2+mc1.18.2
		tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc1.18.2
		walllanterns: Lanterns Belong on Walls 1.0.0
		waystones: Waystones 10.0.0
		yigd: You're in Grave Danger 1.3.1
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.13.3-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2070/PCIe/SSE2 GL version 3.2.0 NVIDIA 496.49, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Deegenerate'/207, l='ServerLevel[small and soft]', x=3047.30, y=67.00, z=8031.30]]
	Data Packs: vanilla
	World Generation: Stable

**Comment by garogan** [comment]
Above log is for it actually just happened again with a stack of 8 charcoal, strangely :/

**Comment by kwpugh** [comment]
did you try without quilt?  not sure if my mods are compatible with quilt.

**Comment by kwpugh** [comment]
I tried with and without quilt and other mods and I cannot replicate this issue.
